// Generated by gencpp from file pathing/PixyResolution.msg
// DO NOT EDIT!


#ifndef PATHING_MESSAGE_PIXYRESOLUTION_H
#define PATHING_MESSAGE_PIXYRESOLUTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pathing
{
template <class ContainerAllocator>
struct PixyResolution_
{
  typedef PixyResolution_<ContainerAllocator> Type;

  PixyResolution_()
    : width(0)
    , height(0)  {
    }
  PixyResolution_(const ContainerAllocator& _alloc)
    : width(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef uint16_t _width_type;
  _width_type width;

   typedef uint16_t _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::pathing::PixyResolution_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pathing::PixyResolution_<ContainerAllocator> const> ConstPtr;

}; // struct PixyResolution_

typedef ::pathing::PixyResolution_<std::allocator<void> > PixyResolution;

typedef boost::shared_ptr< ::pathing::PixyResolution > PixyResolutionPtr;
typedef boost::shared_ptr< ::pathing::PixyResolution const> PixyResolutionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pathing::PixyResolution_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pathing::PixyResolution_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pathing::PixyResolution_<ContainerAllocator1> & lhs, const ::pathing::PixyResolution_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pathing::PixyResolution_<ContainerAllocator1> & lhs, const ::pathing::PixyResolution_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pathing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pathing::PixyResolution_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pathing::PixyResolution_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pathing::PixyResolution_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pathing::PixyResolution_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pathing::PixyResolution_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pathing::PixyResolution_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pathing::PixyResolution_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20cde1cc3b01e7f015e45dc31f8ca17d";
  }

  static const char* value(const ::pathing::PixyResolution_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20cde1cc3b01e7f0ULL;
  static const uint64_t static_value2 = 0x15e45dc31f8ca17dULL;
};

template<class ContainerAllocator>
struct DataType< ::pathing::PixyResolution_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pathing/PixyResolution";
  }

  static const char* value(const ::pathing::PixyResolution_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pathing::PixyResolution_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 width\n"
"uint16 height\n"
;
  }

  static const char* value(const ::pathing::PixyResolution_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pathing::PixyResolution_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PixyResolution_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pathing::PixyResolution_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pathing::PixyResolution_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATHING_MESSAGE_PIXYRESOLUTION_H
