name: slam-toolbox-melodic
version: '1.1.3'
summary: Slam Toolbox
description: |
  A toolbox for building high quality maps of large spaces with a LIDAR.

grade: stable
confinement: classic
base: core18
type: app

apps:
  slam-toolbox-online-sync:
    command: roslaunch --wait slam_toolbox online_sync.launch
    environment: 
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu  # pluginlib (lapack, blas)
    plugs: [network, network-bind]

  slam-toolbox-online-async:
    command: roslaunch --wait slam_toolbox online_async.launch
    environment: 
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu  # pluginlib (lapack, blas)
    plugs: [network, network-bind]

  slam-toolbox-offline:
    command: roslaunch --wait slam_toolbox offline.launch
    environment: 
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu  # pluginlib (lapack, blas)
    plugs: [network, network-bind]

  slam-toolbox-localization:
    command: roslaunch --wait slam_toolbox localization.launch
    environment: 
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu  # pluginlib (lapack, blas)
    plugs: [network, network-bind]

parts:
  workspace:
    build-packages: [qt5-default, libgoogle-glog-dev, liblapack-dev, libblas-dev, libpthread-stubs0-dev] 
    stage-packages: [qt5-default, libgoogle-glog-dev, liblapack-dev, libblas-dev, libpthread-stubs0-dev] 
    plugin: catkin
    source-space: src
    include-roscore: true
    source: .
    catkin-ros-master-uri: http://localhost:11311
    catkin-packages: [slam_toolbox]
    recursive-rosinstall: false
