# Another example configuration file, though this one is used to test the dynamic reconfiguration
# of the ackermann_cmd_mux. Used with reconfigure.launch.

subscribers:
  - name:        "Default input"
    topic:       "input/default"
    timeout:     0.1
    priority:    0
    short_desc:  "The default ackermann_cmd, controllers unaware that we are multiplexing ackermann_cmd should come here"
  - name:        "Navigation stack"
    topic:       "input/navigation"
    timeout:     0.5
    priority:    1
    short_desc:  "Navigation stack controller"
  - name:        "Drive command"
    topic:       "input/drive"
    timeout:     10
    priority:    5
    short_desc:  "Ackermann drive stamped messages from one of velma's several path planners" 
  - name:        "Safety controller"
    topic:       "input/safety"
    timeout:     0.1
    priority:    10
    short_desc:  "Used with the reactive velocity control provided by the bumper/cliff sensor safety controller"
