// Generated by gencpp from file slam_toolbox_msgs/AddSubmap.msg
// DO NOT EDIT!


#ifndef SLAM_TOOLBOX_MSGS_MESSAGE_ADDSUBMAP_H
#define SLAM_TOOLBOX_MSGS_MESSAGE_ADDSUBMAP_H

#include <ros/service_traits.h>


#include <slam_toolbox_msgs/AddSubmapRequest.h>
#include <slam_toolbox_msgs/AddSubmapResponse.h>


namespace slam_toolbox_msgs
{

struct AddSubmap
{

typedef AddSubmapRequest Request;
typedef AddSubmapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddSubmap
} // namespace slam_toolbox_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam_toolbox_msgs::AddSubmap > {
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::slam_toolbox_msgs::AddSubmap&) { return value(); }
};

template<>
struct DataType< ::slam_toolbox_msgs::AddSubmap > {
  static const char* value()
  {
    return "slam_toolbox_msgs/AddSubmap";
  }

  static const char* value(const ::slam_toolbox_msgs::AddSubmap&) { return value(); }
};


// service_traits::MD5Sum< ::slam_toolbox_msgs::AddSubmapRequest> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::AddSubmap >
template<>
struct MD5Sum< ::slam_toolbox_msgs::AddSubmapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::AddSubmap >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::AddSubmapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::AddSubmapRequest> should match
// service_traits::DataType< ::slam_toolbox_msgs::AddSubmap >
template<>
struct DataType< ::slam_toolbox_msgs::AddSubmapRequest>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::AddSubmap >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::AddSubmapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam_toolbox_msgs::AddSubmapResponse> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::AddSubmap >
template<>
struct MD5Sum< ::slam_toolbox_msgs::AddSubmapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::AddSubmap >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::AddSubmapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::AddSubmapResponse> should match
// service_traits::DataType< ::slam_toolbox_msgs::AddSubmap >
template<>
struct DataType< ::slam_toolbox_msgs::AddSubmapResponse>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::AddSubmap >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::AddSubmapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_TOOLBOX_MSGS_MESSAGE_ADDSUBMAP_H
