// Generated by gencpp from file slam_toolbox_msgs/Clear.msg
// DO NOT EDIT!


#ifndef SLAM_TOOLBOX_MSGS_MESSAGE_CLEAR_H
#define SLAM_TOOLBOX_MSGS_MESSAGE_CLEAR_H

#include <ros/service_traits.h>


#include <slam_toolbox_msgs/ClearRequest.h>
#include <slam_toolbox_msgs/ClearResponse.h>


namespace slam_toolbox_msgs
{

struct Clear
{

typedef ClearRequest Request;
typedef ClearResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Clear
} // namespace slam_toolbox_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam_toolbox_msgs::Clear > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::slam_toolbox_msgs::Clear&) { return value(); }
};

template<>
struct DataType< ::slam_toolbox_msgs::Clear > {
  static const char* value()
  {
    return "slam_toolbox_msgs/Clear";
  }

  static const char* value(const ::slam_toolbox_msgs::Clear&) { return value(); }
};


// service_traits::MD5Sum< ::slam_toolbox_msgs::ClearRequest> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::Clear >
template<>
struct MD5Sum< ::slam_toolbox_msgs::ClearRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::Clear >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ClearRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::ClearRequest> should match
// service_traits::DataType< ::slam_toolbox_msgs::Clear >
template<>
struct DataType< ::slam_toolbox_msgs::ClearRequest>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::Clear >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ClearRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam_toolbox_msgs::ClearResponse> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::Clear >
template<>
struct MD5Sum< ::slam_toolbox_msgs::ClearResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::Clear >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ClearResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::ClearResponse> should match
// service_traits::DataType< ::slam_toolbox_msgs::Clear >
template<>
struct DataType< ::slam_toolbox_msgs::ClearResponse>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::Clear >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ClearResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_TOOLBOX_MSGS_MESSAGE_CLEAR_H
