// Generated by gencpp from file slam_toolbox_msgs/LoopClosure.msg
// DO NOT EDIT!


#ifndef SLAM_TOOLBOX_MSGS_MESSAGE_LOOPCLOSURE_H
#define SLAM_TOOLBOX_MSGS_MESSAGE_LOOPCLOSURE_H

#include <ros/service_traits.h>


#include <slam_toolbox_msgs/LoopClosureRequest.h>
#include <slam_toolbox_msgs/LoopClosureResponse.h>


namespace slam_toolbox_msgs
{

struct LoopClosure
{

typedef LoopClosureRequest Request;
typedef LoopClosureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoopClosure
} // namespace slam_toolbox_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam_toolbox_msgs::LoopClosure > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::slam_toolbox_msgs::LoopClosure&) { return value(); }
};

template<>
struct DataType< ::slam_toolbox_msgs::LoopClosure > {
  static const char* value()
  {
    return "slam_toolbox_msgs/LoopClosure";
  }

  static const char* value(const ::slam_toolbox_msgs::LoopClosure&) { return value(); }
};


// service_traits::MD5Sum< ::slam_toolbox_msgs::LoopClosureRequest> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::LoopClosure >
template<>
struct MD5Sum< ::slam_toolbox_msgs::LoopClosureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::LoopClosure >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::LoopClosureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::LoopClosureRequest> should match
// service_traits::DataType< ::slam_toolbox_msgs::LoopClosure >
template<>
struct DataType< ::slam_toolbox_msgs::LoopClosureRequest>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::LoopClosure >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::LoopClosureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam_toolbox_msgs::LoopClosureResponse> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::LoopClosure >
template<>
struct MD5Sum< ::slam_toolbox_msgs::LoopClosureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::LoopClosure >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::LoopClosureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::LoopClosureResponse> should match
// service_traits::DataType< ::slam_toolbox_msgs::LoopClosure >
template<>
struct DataType< ::slam_toolbox_msgs::LoopClosureResponse>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::LoopClosure >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::LoopClosureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_TOOLBOX_MSGS_MESSAGE_LOOPCLOSURE_H
