// Generated by gencpp from file slam_toolbox_msgs/MergeMaps.msg
// DO NOT EDIT!


#ifndef SLAM_TOOLBOX_MSGS_MESSAGE_MERGEMAPS_H
#define SLAM_TOOLBOX_MSGS_MESSAGE_MERGEMAPS_H

#include <ros/service_traits.h>


#include <slam_toolbox_msgs/MergeMapsRequest.h>
#include <slam_toolbox_msgs/MergeMapsResponse.h>


namespace slam_toolbox_msgs
{

struct MergeMaps
{

typedef MergeMapsRequest Request;
typedef MergeMapsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MergeMaps
} // namespace slam_toolbox_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam_toolbox_msgs::MergeMaps > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::slam_toolbox_msgs::MergeMaps&) { return value(); }
};

template<>
struct DataType< ::slam_toolbox_msgs::MergeMaps > {
  static const char* value()
  {
    return "slam_toolbox_msgs/MergeMaps";
  }

  static const char* value(const ::slam_toolbox_msgs::MergeMaps&) { return value(); }
};


// service_traits::MD5Sum< ::slam_toolbox_msgs::MergeMapsRequest> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::MergeMaps >
template<>
struct MD5Sum< ::slam_toolbox_msgs::MergeMapsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::MergeMaps >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::MergeMapsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::MergeMapsRequest> should match
// service_traits::DataType< ::slam_toolbox_msgs::MergeMaps >
template<>
struct DataType< ::slam_toolbox_msgs::MergeMapsRequest>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::MergeMaps >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::MergeMapsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam_toolbox_msgs::MergeMapsResponse> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::MergeMaps >
template<>
struct MD5Sum< ::slam_toolbox_msgs::MergeMapsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::MergeMaps >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::MergeMapsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::MergeMapsResponse> should match
// service_traits::DataType< ::slam_toolbox_msgs::MergeMaps >
template<>
struct DataType< ::slam_toolbox_msgs::MergeMapsResponse>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::MergeMaps >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::MergeMapsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_TOOLBOX_MSGS_MESSAGE_MERGEMAPS_H
