// Generated by gencpp from file slam_toolbox_msgs/SaveMap.msg
// DO NOT EDIT!


#ifndef SLAM_TOOLBOX_MSGS_MESSAGE_SAVEMAP_H
#define SLAM_TOOLBOX_MSGS_MESSAGE_SAVEMAP_H

#include <ros/service_traits.h>


#include <slam_toolbox_msgs/SaveMapRequest.h>
#include <slam_toolbox_msgs/SaveMapResponse.h>


namespace slam_toolbox_msgs
{

struct SaveMap
{

typedef SaveMapRequest Request;
typedef SaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMap
} // namespace slam_toolbox_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam_toolbox_msgs::SaveMap > {
  static const char* value()
  {
    return "0fce35bd9f5b27a63eb9b0e831759a0b";
  }

  static const char* value(const ::slam_toolbox_msgs::SaveMap&) { return value(); }
};

template<>
struct DataType< ::slam_toolbox_msgs::SaveMap > {
  static const char* value()
  {
    return "slam_toolbox_msgs/SaveMap";
  }

  static const char* value(const ::slam_toolbox_msgs::SaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::slam_toolbox_msgs::SaveMapRequest> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::SaveMap >
template<>
struct MD5Sum< ::slam_toolbox_msgs::SaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::SaveMap >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::SaveMapRequest> should match
// service_traits::DataType< ::slam_toolbox_msgs::SaveMap >
template<>
struct DataType< ::slam_toolbox_msgs::SaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::SaveMap >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam_toolbox_msgs::SaveMapResponse> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::SaveMap >
template<>
struct MD5Sum< ::slam_toolbox_msgs::SaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::SaveMap >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::SaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::SaveMapResponse> should match
// service_traits::DataType< ::slam_toolbox_msgs::SaveMap >
template<>
struct DataType< ::slam_toolbox_msgs::SaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::SaveMap >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::SaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_TOOLBOX_MSGS_MESSAGE_SAVEMAP_H
