// Generated by gencpp from file slam_toolbox_msgs/SerializePoseGraph.msg
// DO NOT EDIT!


#ifndef SLAM_TOOLBOX_MSGS_MESSAGE_SERIALIZEPOSEGRAPH_H
#define SLAM_TOOLBOX_MSGS_MESSAGE_SERIALIZEPOSEGRAPH_H

#include <ros/service_traits.h>


#include <slam_toolbox_msgs/SerializePoseGraphRequest.h>
#include <slam_toolbox_msgs/SerializePoseGraphResponse.h>


namespace slam_toolbox_msgs
{

struct SerializePoseGraph
{

typedef SerializePoseGraphRequest Request;
typedef SerializePoseGraphResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SerializePoseGraph
} // namespace slam_toolbox_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam_toolbox_msgs::SerializePoseGraph > {
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::slam_toolbox_msgs::SerializePoseGraph&) { return value(); }
};

template<>
struct DataType< ::slam_toolbox_msgs::SerializePoseGraph > {
  static const char* value()
  {
    return "slam_toolbox_msgs/SerializePoseGraph";
  }

  static const char* value(const ::slam_toolbox_msgs::SerializePoseGraph&) { return value(); }
};


// service_traits::MD5Sum< ::slam_toolbox_msgs::SerializePoseGraphRequest> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::SerializePoseGraph >
template<>
struct MD5Sum< ::slam_toolbox_msgs::SerializePoseGraphRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::SerializePoseGraph >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::SerializePoseGraphRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::SerializePoseGraphRequest> should match
// service_traits::DataType< ::slam_toolbox_msgs::SerializePoseGraph >
template<>
struct DataType< ::slam_toolbox_msgs::SerializePoseGraphRequest>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::SerializePoseGraph >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::SerializePoseGraphRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam_toolbox_msgs::SerializePoseGraphResponse> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::SerializePoseGraph >
template<>
struct MD5Sum< ::slam_toolbox_msgs::SerializePoseGraphResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::SerializePoseGraph >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::SerializePoseGraphResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::SerializePoseGraphResponse> should match
// service_traits::DataType< ::slam_toolbox_msgs::SerializePoseGraph >
template<>
struct DataType< ::slam_toolbox_msgs::SerializePoseGraphResponse>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::SerializePoseGraph >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::SerializePoseGraphResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_TOOLBOX_MSGS_MESSAGE_SERIALIZEPOSEGRAPH_H
