// Generated by gencpp from file slam_toolbox_msgs/ToggleInteractive.msg
// DO NOT EDIT!


#ifndef SLAM_TOOLBOX_MSGS_MESSAGE_TOGGLEINTERACTIVE_H
#define SLAM_TOOLBOX_MSGS_MESSAGE_TOGGLEINTERACTIVE_H

#include <ros/service_traits.h>


#include <slam_toolbox_msgs/ToggleInteractiveRequest.h>
#include <slam_toolbox_msgs/ToggleInteractiveResponse.h>


namespace slam_toolbox_msgs
{

struct ToggleInteractive
{

typedef ToggleInteractiveRequest Request;
typedef ToggleInteractiveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleInteractive
} // namespace slam_toolbox_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam_toolbox_msgs::ToggleInteractive > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::slam_toolbox_msgs::ToggleInteractive&) { return value(); }
};

template<>
struct DataType< ::slam_toolbox_msgs::ToggleInteractive > {
  static const char* value()
  {
    return "slam_toolbox_msgs/ToggleInteractive";
  }

  static const char* value(const ::slam_toolbox_msgs::ToggleInteractive&) { return value(); }
};


// service_traits::MD5Sum< ::slam_toolbox_msgs::ToggleInteractiveRequest> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::ToggleInteractive >
template<>
struct MD5Sum< ::slam_toolbox_msgs::ToggleInteractiveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::ToggleInteractive >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ToggleInteractiveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::ToggleInteractiveRequest> should match
// service_traits::DataType< ::slam_toolbox_msgs::ToggleInteractive >
template<>
struct DataType< ::slam_toolbox_msgs::ToggleInteractiveRequest>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::ToggleInteractive >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ToggleInteractiveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam_toolbox_msgs::ToggleInteractiveResponse> should match
// service_traits::MD5Sum< ::slam_toolbox_msgs::ToggleInteractive >
template<>
struct MD5Sum< ::slam_toolbox_msgs::ToggleInteractiveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slam_toolbox_msgs::ToggleInteractive >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ToggleInteractiveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_toolbox_msgs::ToggleInteractiveResponse> should match
// service_traits::DataType< ::slam_toolbox_msgs::ToggleInteractive >
template<>
struct DataType< ::slam_toolbox_msgs::ToggleInteractiveResponse>
{
  static const char* value()
  {
    return DataType< ::slam_toolbox_msgs::ToggleInteractive >::value();
  }
  static const char* value(const ::slam_toolbox_msgs::ToggleInteractiveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_TOOLBOX_MSGS_MESSAGE_TOGGLEINTERACTIVE_H
